### ISSUE TITLE
Navigation via browser button and location

### ISSUE THREAD

**Issue by MaTo04** [darioegb/ngx-translate-routes#10]
Hi @darioegb,

i do some research for the navigation issues. There are two parts. The first is, if i use "location.back()" from "@angular/common" there is no translation behind. And the second issue is the usage of the back and forward buttons from the browser (in my case Google Chrome), there is also no translation behind. And if i go forward the application tries to navigate to the translated route and not the "original" route keys. 

For the first issue its mostly possible to replace location with the router.navigate() but it would be nice if it works so for generalized components with different parents.
 
But for the second issue i dont have any ideas.

**Comment by darioegb** [comment]
Interesting bug, thanks for reporting it. I'll take a look at it as soon as I can. The lib only stores the last path that was accessed in the localstorage. Maybe it should handle the history to be able to solve this case, or at least the previous and the next one.

**Comment by darioegb** [comment]
Hi @MaTo04 just fly I’m do some research to this issue and I have a probably solution.

**Comment by MaTo04** [comment]
@darioegb In general it works but if i start the Application or navigate to the baseroute (e.g. http://localhost:4200/) from everywhere i get the message: 

`"TypeError: a is not iterable\n at N.allWithCallback (http://localhost:4200/polyfills.js:2:1906)\n at N.all (http://localhost:4200/polyfills.js:2:1610)\n at v.<anonymous> (http://localhost:4200/main.js:22:8969)\n at Generator.next (<anonymous>)\n at http://localhost:4200/chunk-V6QL2RSM.js:1:2007\n at new N (http://localhost:4200/polyfills.js:2:2234)\n at t7 (http://localhost:4200/chunk-V6QL2RSM.js:1:1827)\n at v.translateRoute (http://localhost:4200/main.js:22:8649)\n at _.checkConfigValueAndMakeTranslations (http://localhost:4200/main.js:22:11656)\n at Object.next (http://localhost:4200/main.js:22:11456)"`

It seems there is a missing testcase if no route is entered.

**Comment by darioegb** [comment]
Hi @MaTo04 In the routes file, do you not have any redirection defined when going to the base route or a route defined for the base route? Or if you don't have any route defined for the base route, it gives you this problem as I understand it.

**Comment by MaTo04** [comment]
Hi @darioegb my application is something like a WebGIS. There is no redirection defined. By starting the application a (map) component is loaded to the app.component.html. From these "landing-page" (like google maps or osm) i start my navigation. But if i go back to the initial map view im on the base route. 
As workaround i could redirect to something like a container route but this doesn´t solve the problem.

**Comment by darioegb** [comment]
Hi @MaTo04 I have released a new version that prevents translation attempts when the application is in the root path. I trust it resolves your issue.

**Comment by MaTo04** [comment]
Hi @darioegb. Its perfect, i test it and it works great. Now i can finally make an overall test in my application.
