### ISSUE TITLE
Missing translation with url params

### ISSUE THREAD

**Issue by MaTo04** [darioegb/ngx-translate-routes#11]
It seems that the last route element is not translated as soon as query parameters are given. I would assume that a split at ? is missing. For example:

http://localhost:4200/aboutUs?Name=Test

I think it would be done if you add an if in the ngx-translate-routes-route.service.ts (Line 32) like below (I dont test it):

`const subPaths = this.#router.url.includes('?') ? this.#router.url.split('?')[0].split('/') : this.#router.url.split('/')`

**Comment by MaTo04** [comment]
In my opinion, it would be best to only translate the route and, if possible, make the translation of the query parameters optional. To do this, I would add an additional boolean variable to the NgxTranslateRoutesConfig, which makes translation possible. To follow your logic, I would probably name it “enableQueryParamsTranslate:? boolean”. Maybe you could alsow allow a queryParamPrefix, if somebody need it.

**Comment by darioegb** [comment]
Ok thanks for your reply I’ll take a look as soon as possible. I like the idea of optional translate params.

**Comment by MaTo04** [comment]
First of all, thank you @darioegb for the fast reaction and implementation. 

I think there is an issue with the new implementation. If if initialize my project i get the error message: 
`Yt(...).call(...).find is not a function`

And if i try to navigate in my project i get the following error message:
`K.findIndex is not a function`

The new option "enableQueryParamsTrans" is set to false. Maybe it could also affected by [#10 Navigation via browser button and location](https://github.com/darioegb/ngx-translate-routes/issues/10)

**Comment by darioegb** [comment]
Hi @MaTo04.
 No problem. Try cleaning the local storage, it seems to me that the problem comes from there. Since the format of the structure that is cached was changed.

**Comment by MaTo04** [comment]
@darioegb i test it without translate the query parameters and it works very well. Thanks for it.
