### ISSUE TITLE
Upgrade Angular 17 > 18

### ISSUE THREAD

**Issue by MaTo04** [darioegb/ngx-translate-routes#8]
Do you plan an upgrade to Angular 18 ?

**Comment by darioegb** [comment]
Hi @MaTo04, yes, I'll do that as soon as possible, most likely within this month. 
Are you facing any problems with Angular 18?

**Comment by MaTo04** [comment]
First of all, i use ngx-translate for a long time. Now its necessary to translate the routes. So i searched for packages and find yours, which i think, is very easy to use. I played a bit with the stackblitz example but this is also a very old version. I tried to upgrade the packages and remove the deprecated part (HttpClientModule in app.module.ts). Please have a look and if you confirm with it, please renew the stackblitz example. I attached the stackblitz files. 

[ngx-translate-routes-example-qgeccm.zip](https://github.com/user-attachments/files/15605635/ngx-translate-routes-example-qgeccm.zip)

To answer your question. For now i don´t facing any problems with Angular 18. I have only just started to integrate it in my project.

**Comment by darioegb** [comment]
Great, thank you for sharing the file @MaTo04. I will review it as you mentioned the Stackblitz example is outdated, and I will update it. Additionally, there is a showcase project in the repo that is similar to the Stackblitz example but updated. I appreciate that the library is helpful. If you are willing, you can star the project repo, which would be a great help.

**Comment by MaTo04** [comment]
Perfect. I integrated your Package in my application. There is an issue if i use this.location.back() but i habe to do further investigations before identifying the problem.

**Comment by darioegb** [comment]
Ok thanks if you find the reason feel free to create an issue. Besides I can’t migrate the lib to angular 18 until angular-eslint will be updated.
